---
- !ruby/struct:Config::MetronomeData
  ip: 10.0.1.113
  port: 2000
  rhythm:
  - 1
  - 0
  - 1
  - 0
  - 1
  - 0
  - 1
  - 0
  - 1
  - 0
  - 1
  - 0
  - 1
  - 0
  - 1
  - 0
- !ruby/struct:Config::MetronomeData
  ip: 10.0.1.124
  port: 2001
  rhythm:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
- !ruby/struct:Config::MetronomeData
  ip: 10.0.1.183
  port: 2002
  rhythm:
  - 1
  - 1
  - 1
  - 0
  - 1
  - 1
  - 1
  - 0
  - 1
  - 1
  - 1
  - 0
  - 1
  - 1
  - 1
  - 0
- !ruby/struct:Config::MetronomeData
  ip: 10.0.1.50
  port: 2003
  rhythm:
  - 1
  - 1
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 1
  - 1
  - 0
  - 0
